[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  function = "proxy"   # jméno souboru bez přípony
  path = "/proxy/*"    # veřejná cesta, na kterou bude funkce dostupná

# SPA fallback (React/Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200