backend:
  name: git-gateway
  branch: Hlavni

publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"

locale: "cs"

collections:
  - label: "Blog (Česky)"
    name: "blog_cs"
    files:
      - label: "České články"
        name: "cs_blog"
        file: "src/data/i18n/cs.blog.json"
        fields:
          - label: "Položky"
            name: "items"
            widget: "list"
            summary: "{{fields.title}} ({{fields.date}} • {{fields.category}})"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Název (soubor)", name: "title", widget: "string" }
              - { label: "Datum", name: "date", widget: "date", format: "YYYY-MM-DD" }
              - { label: "Kategorie", name: "category", widget: "string" }
              - { label: "Text", name: "body", widget: "text" }

  - label: "Blog (English)"
    name: "blog_en"
    files:
      - label: "English posts"
        name: "en_blog"
        file: "src/data/i18n/en.blog.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.title}} ({{fields.date}} • {{fields.category}})"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Body", name: "body", widget: "text" }
